/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.testng.annotations.*;

public class AppTest {

    @BeforeGroups
    public void setUp() {
        System.out.println("setup method");
    }

    @Test(
            groups = {"sanity", "regression"},
            priority = 1)
    public void testNumber1() {
        System.out.println("");
    }

    @Test(groups = "smoke")
    public void testNumber2() {
        System.out.println("");
    }

    @Test(groups = "sanity",
            priority = 2)
    @Parameters({"par1", "par2"})
    public void testNumber3(String par1, String par2) {
        System.out.println(par1 + par2);
    }

    @Test(priority = 3)
    public void test3() {
        System.out.println("test #3");
    }

    @DataProvider(name = "data")
    public static Object[][] data() {
        return new Object[][]{
                {"smoke", "sanity"},
                {"sanity", "regression"}
        };
    }

    @AfterGroups(dependsOnGroups = "smoke")
    public void tearDown() {
        System.out.println("teardown method");
    }
}