/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class App {

    public void setUp() {
        System.out.println("setup method");
    }

    public void tearDown() {
        System.out.println("teardown method");
    }
}
